FROM nvcr.io/nvidia/tensorrt:21.05-py3
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && apt install -y qt5-default
RUN pip3 install --upgrade pip

WORKDIR /app
COPY . .
RUN pip3 install -r requirements-trt.txt
CMD bash
